### ISSUE TITLE
Location correction for WRI1006494

### ISSUE THREAD

**Issue by dbaston** [wri/global-power-plant-database#17]
### Issue Type
(mark with x between brackets)
* [X] Proposed Data Correction
* [ ] New Data Source

### Countries

Spain

### Affected plant(s)

WRI1006494

### Database field(s)

Location

### Description

The coordinates for this plant (Garona Verda) fall on the Santa María de Garoña Nuclear Power Plant, probably as a result of fuzzy string matching somewhere.

### Source Information

The actual location appears to be colocated with a fish farm in the town of Les at latitude 42.802499, longitude 0.704113. Source: https://cincodias.elpais.com/cincodias/2002/10/22/empresas/1035293998_850215.html

#### Data Provider
(Select one or more with x between brackets)
* [ ] Official Government Data
* [ ] Utility/Producer Data
* [ ] Non-profit/Independent Group Data
* [ ] Unknown Quality

#### Data Format
(Select one or more with x between brackets)
* [ ] Text on web page
* [ ] Structured web page (table or regular format for data)
* [ ] Machine-readable format (Excel, CSV, XML, ...)
* [ ] Human readable document (PDF, Word, ...)

#### Data Location
(insert URL(s) or source of information)

### Additional Info

(anything else?)

**Comment by loganbyers** [comment]
Thanks for the correction. The error was indeed because of a fuzzy string match! Looks like the Garona Nuclear Plant has been shut down for a while anyways, so no need to add it.
