### ISSUE TITLE
The powerexplorer@wri.org email address in the README cannot be sent to

### ISSUE THREAD

**Issue by simonw** [wri/global-power-plant-database#9]
Hello,

I just tried to send an email to powerexplorer@wri.org (which is linked to in your README) and got the following error:

![2018-05-23 at 11 02 am](https://user-images.githubusercontent.com/9599/40443018-e5136ce2-5e79-11e8-98c6-c5a52005c0e7.png)

Here's the email I tried to send you:

----

I built something fun using your Global Power Plant Database.

https://global-power-plants.datasettes.com/global-power-plants-afbd345/global-power-plants

It's a UI for running faceted searches against the full set of 25,000 power plants and visualizing them on a map. It also provides a JSON API for querying the data... and you can even run your own custom SQL against it, e.g. https://global-power-plants.datasettes.com/global-power-plants-afbd345?sql=select+*+from+%5Bglobal-power-plants%5D+where+%22country_long%22+%3D+%22Brazil%22+and+%22fuel1%22+%3D+%22Biomass%22 - select * from [global-power-plants] where "country_long" = "Brazil" and "fuel1" = "Biomass"

This is all running on top of my open-source project Datasette - a toolkit for building this kind of thing against any form of structured data and then publishing it online: https://github.com/simonw/datasette

I've actually automated the process of packaging and deploying your data using Travis CI - here's my GitHub repo which runs automatically once a day
and pulls your latest CSV file, then deploys it using Datasette: https://github.com/simonw/global-power-plants-datasette

I'm REALLY impressed by the quality of your data - and it's a fantastic fit for demonstrating the software I've been building.

**Comment by loganbyers** [comment]
Thanks for pointing this out. I fixed the listserv to allow outside emailers, so you can contact us again through that channel if you want. Closing the issue.

Datasette looks very practical and simple; sqlite is so nice for a read-only application. I have passed this on to other people on the team so they can enjoy it (and hopefully learn some SQL). We are always excited when someone uses our datasets and I agree this is a great demo of your software. Geographic data always clicks for me, but we need some custom map markers! I'll have to look at the docs further and see the capabilities.

WRI has been leading a data platform called [Resource Watch](https://resourcewatch.org/data/explore) that you might find fun to check out. GPPD is on there along with hundreds of other global-scale datasets so there is some cool data fusion that can be done without the SQL (for now).

Feel free to email us if you want to talk further. Thanks for sharing.
